name: Conventional Commits
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    name: "Lint PR Title"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn add @commitlint/config-conventional --ignore-workspace-root-check

      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
