name: Conventional Commits
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@nft42"
          always-auth: true
      - name: Install Dependencies
        run: yarn add @commitlint/config-conventional --ignore-workspace-root-check
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
