name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
    
      - uses: volta-cli/action@v4
    
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      # - name: Create .npmrc
      #   run: |
      #     echo "@verysimple:registry=https://registry.npmjs.org/" > .npmrc
      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
      - name: Publish
        run: yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "ci: Update package versions" || echo "No changes to commit"
          git push