name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v4

      - name: Install Root Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Package Dependencies
        run: yarn lerna bootstrap

      - name: Run builds
        run: yarn lerna exec yarn build

      - name: Version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          git config user.name "Ben Tatum"
          git config user.email "mail@benjtatum.com"
          yarn lerna publish --yes
