name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@nft42"
          always-auth: true
      - name: Use Yarn Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Root Dependencies
        run: yarn install --frozen-lockfile
      - name: Install Package Dependencies
        run: yarn lerna bootstrap
      - name: Run builds
        run: yarn lerna exec yarn build
      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          yarn lerna publish --conventional-commits -m "chore(release): published by lerna" --yes
