name: Install, Build & Test
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build-and-test:
    name: "Run"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Pacakge Dependencies
        run: yarn bootstrap

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Generate coverage badges
        run: yarn make-badges:ci
